# Generated by Django 5.0.1 on 2024-01-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_semester_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
