# Generated by Django 5.0.1 on 2024-01-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
